### ISSUE TITLE
does kdsep support the snapshot feature of rocksdb?

### ISSUE THREAD

**Issue by wangnengjie** [adslabcuhk/kdsep#1]
For implementation of LSM tree like leveldb or rocksdb, snapshot is a useful feature in many use case. During compaction, rocksdb will not compact data with higher seq number (each snapshot associated with a sequence number).

Aside from this, each Get or iterator op will hold a sequence number and a version ref so that SST files will not be deleted after compaction. Consider a long term iterator (not recommended), we should guarantee it can access old data.

So i wonder whether kdsep takes these into consideration during data flush (from write buffer) and the GC of buckets.

**Comment by NeverMore2744** [comment]
Thank you for asking the question. For now, KDSep does not support the snapshot feature. The main reason is that each bucket is not immutable (i.e., a bucket can be modified during data flush and GC), unlike SSTs in RocksDB or LevelDB. Although we introduce sequence numbers, they are mainly used for crash recovery instead of snapshots.

It is possible to support such a feature after some engineering work. Since we already have sequence numbers in buckets, a possible approach is to create snapshots of buckets and prevent erasing old data during GC. The potential overhead is that it needs extra memory to keep per-bucket bloom filters for each snapshot created.

**Comment by wangnengjie** [comment]
Okay, i get it. Thanks for your reply.
